#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4

bspc config border_width 1
bspc config window_gap 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

hsetroot -solid '#0F1620'

killall -q polybar

while pgrep -u $UID x polybar >/dev/null; do
	sleep 1
done

polybar -c ~/.config/polybar/config main &
